/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mathmaze;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author SANDEEPA
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();

        //center the form of the window
        this.setLocationRelativeTo(null);

    }
// --------------------------------------------------------------------------image locatiion of buttons
    ImageIcon initialIcon_minimize = new ImageIcon("C:\\Users\\sanju\\Documents\\NetBeansProjects\\MathMaze\\src\\images\\LbL_images\\Minimize button.png");
    ImageIcon hoverIcon_minimize = new ImageIcon("C:\\Users\\sanju\\Documents\\NetBeansProjects\\MathMaze\\src\\images\\LbL_images\\Minimize button after clicking.png");

    ImageIcon initialIcon_close = new ImageIcon("C:\\Users\\sanju\\Documents\\NetBeansProjects\\MathMaze\\src\\images\\LbL_images\\Exit button.png");
    ImageIcon hoverIcon_close = new ImageIcon("C:\\Users\\sanju\\Documents\\NetBeansProjects\\MathMaze\\src\\images\\LbL_images\\Exit button after clicking.png");

    ImageIcon initialIcon_previous = new ImageIcon("C:\\Users\\sanju\\Documents\\NetBeansProjects\\MathMaze\\src\\images\\LbL_images\\Lbl_button_previous.png");
    ImageIcon hoverIcon_previous = new ImageIcon("C:\\Users\\sanju\\Documents\\NetBeansProjects\\MathMaze\\src\\images\\LbL_images\\Lbl_button_previous_afterClicking.png");

    ImageIcon initialIcon_login = new ImageIcon("C:\\Users\\sanju\\Documents\\NetBeansProjects\\MathMaze\\src\\images\\LbL_images\\lbl_loginButton.png");
    ImageIcon hoverIcon_login = new ImageIcon("C:\\Users\\sanju\\Documents\\NetBeansProjects\\MathMaze\\src\\images\\LbL_images\\lbl_loginButton_afterClicking.png");

    ImageIcon initialIcon_registerNow = new ImageIcon("C:\\Users\\sanju\\Documents\\NetBeansProjects\\MathMaze\\src\\images\\LbL_images\\lbl_Register_Now_button.png");
    ImageIcon hoverIcon_registerNow = new ImageIcon("C:\\Users\\sanju\\Documents\\NetBeansProjects\\MathMaze\\src\\images\\LbL_images\\lbl_Register_Now_button_afterClicking.png");

    private void showMessageDialogWithTimer(String username) {
        String message = "Hi, " + username;

        JOptionPane optionPane = new JOptionPane(message, JOptionPane.INFORMATION_MESSAGE);
        JDialog dialog = optionPane.createDialog("WELCOME");

        Timer timer = new Timer(2000, (ActionEvent e) -> {
            dialog.dispose();
        });
        timer.setRepeats(false);
        timer.start();

        dialog.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_LoginTitle = new javax.swing.JLabel();
        jLabel4_LoginUser = new javax.swing.JLabel();
        jLabel5_LoginPass = new javax.swing.JLabel();
        jTextField_user = new javax.swing.JTextField();
        jPasswordField_Pass = new javax.swing.JPasswordField();
        jLabel_loginButton = new javax.swing.JLabel();
        jLabel_RegisterHere = new javax.swing.JLabel();
        jLabel6_RegisterLink = new javax.swing.JLabel();
        jLabel_minimizeClick = new javax.swing.JLabel();
        jLabel_CloseClick = new javax.swing.JLabel();
        jLabel_previousPage = new javax.swing.JLabel();
        jLabel1_LoginBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1_LoginTitle.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel1_LoginTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LoginFormLabel.png"))); // NOI18N
        getContentPane().add(jLabel1_LoginTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 340, 80));

        jLabel4_LoginUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/username.png"))); // NOI18N
        getContentPane().add(jLabel4_LoginUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 50, 50));

        jLabel5_LoginPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Password.png"))); // NOI18N
        getContentPane().add(jLabel5_LoginPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 50, 50));

        jTextField_user.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_user.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jTextField_user.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_user.setText("username");
        jTextField_user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_userFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_userFocusLost(evt);
            }
        });
        getContentPane().add(jTextField_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 270, 50));

        jPasswordField_Pass.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordField_Pass.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jPasswordField_Pass.setForeground(new java.awt.Color(102, 102, 102));
        jPasswordField_Pass.setText("Password");
        jPasswordField_Pass.setToolTipText("username");
        jPasswordField_Pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_PassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_PassFocusLost(evt);
            }
        });
        getContentPane().add(jPasswordField_Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 270, 50));

        jLabel_loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LbL_images/lbl_loginButton.png"))); // NOI18N
        jLabel_loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_loginButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_loginButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_loginButtonMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 260, 80));

        jLabel_RegisterHere.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel_RegisterHere.setForeground(new java.awt.Color(255, 255, 0));
        jLabel_RegisterHere.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LbL_images/lbl_Register_Now_button.png"))); // NOI18N
        jLabel_RegisterHere.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_RegisterHere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_RegisterHereMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_RegisterHereMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_RegisterHereMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_RegisterHere, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, 190, 40));

        jLabel6_RegisterLink.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel6_RegisterLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Label_Don’t you have an account_ Register from here.png"))); // NOI18N
        getContentPane().add(jLabel6_RegisterLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 390, 90));

        jLabel_minimizeClick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LbL_images/Minimize button.png"))); // NOI18N
        jLabel_minimizeClick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimizeClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeClickMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_minimizeClickMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_minimizeClickMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_minimizeClick, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 40, 40));

        jLabel_CloseClick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LbL_images/Exit button.png"))); // NOI18N
        jLabel_CloseClick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_CloseClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseClickMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_CloseClickMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_CloseClickMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_CloseClick, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 40, 40));

        jLabel_previousPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LbL_images/Lbl_button_previous.png"))); // NOI18N
        jLabel_previousPage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_previousPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_previousPageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_previousPageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_previousPageMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_previousPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        jLabel1_LoginBackground.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1_LoginBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Background_Loging.png"))); // NOI18N
        getContentPane().add(jLabel1_LoginBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //-------------------------------------------------get the user's input data
    
    private void jTextField_userFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_userFocusGained

        //clear the textfield on focus if the text is "username"
        if (jTextField_user.getText().trim().toLowerCase().equals("username")) {
            jTextField_user.setText("");
            jTextField_user.setForeground(Color.black);
        }
        //create a green border for username input box
        Border jtextBox = BorderFactory.createMatteBorder(3, 3, 3, 3, Color.green);
        jTextField_user.setBorder(jtextBox );
        
        //set a green border to the LoginUser
        Border jlabel_icon = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.green);
        jLabel4_LoginUser.setBorder(jlabel_icon);
    }//GEN-LAST:event_jTextField_userFocusGained

    private void jTextField_userFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_userFocusLost

        //if the textfield is equal to "username" or empty
        //--------------------------it will set the "username" text in the field
        if (jTextField_user.getText().trim().equals("") || jTextField_user.getText().trim().toLowerCase().equals("username")) {
            jTextField_user.setText("username");
            jTextField_user.setForeground(new Color(153, 153, 153));
        }
        //create a black color to the border
        Border jtextBox = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
        jTextField_user.setBorder(jtextBox );
        
        //set the black border to user icon
        Border LoginUser_icon = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(51,51,51));
        jLabel4_LoginUser.setBorder(LoginUser_icon);

    }//GEN-LAST:event_jTextField_userFocusLost

    //----------  ---------------------------------inpust user's password field
    
    private void jPasswordField_PassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_PassFocusGained

        // get the password text
        String pass = String.valueOf(jPasswordField_Pass.getPassword());

        if (pass.trim().toLowerCase().equals("password")) {
            jPasswordField_Pass.setText("");
            jPasswordField_Pass.setForeground(Color.black);
        }
        //create green border to the password box
        Border jpasswordBox = BorderFactory.createMatteBorder(3, 3, 3, 3, Color.green);
        jPasswordField_Pass.setBorder(jpasswordBox );
        
        //set a green border to the LoginPass icon
        Border jlabel_icon = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.green);
        jLabel5_LoginPass.setBorder(jlabel_icon);
    }//GEN-LAST:event_jPasswordField_PassFocusGained

    private void jPasswordField_PassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_PassFocusLost

        //get the password text
        String pass = String.valueOf(jPasswordField_Pass.getPassword()); 
        //if the passwordfield is equal to "password" or empty
        // it will set the "password" text in the field
        if (pass.trim().equals("") || pass.trim().toLowerCase().equals("password")) {
            jPasswordField_Pass.setText("password");
            jPasswordField_Pass.setForeground(new Color(153, 153, 153));
        }
        //create black border to the passwordbox
        Border jpasswordBox = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
        jPasswordField_Pass.setBorder(jpasswordBox );
        
        //create a black border to the password icon
        Border LoginPass_icon = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(51,51,51));
        jLabel5_LoginPass.setBorder(LoginPass_icon);
    }//GEN-LAST:event_jPasswordField_PassFocusLost
    /**/

    //------------------------------------register label functionion as a button
    private void jLabel_RegisterHereMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RegisterHereMouseEntered

        jLabel_RegisterHere.setIcon(hoverIcon_registerNow);
    }//GEN-LAST:event_jLabel_RegisterHereMouseEntered

    private void jLabel_RegisterHereMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RegisterHereMouseExited

        jLabel_RegisterHere.setIcon(initialIcon_registerNow);
    }//GEN-LAST:event_jLabel_RegisterHereMouseExited

    private void jLabel_RegisterHereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RegisterHereMouseClicked

        //click the button to enter the Register Form
        RegistrationForm Rf = new RegistrationForm();
        Rf.setVisible(true);
        Rf.pack();
        Rf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel_RegisterHereMouseClicked

    //---------------------------------------------------------minimize the form
    
    private void jLabel_minimizeClickMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeClickMouseEntered
        jLabel_minimizeClick.setIcon(hoverIcon_minimize);
    }//GEN-LAST:event_jLabel_minimizeClickMouseEntered

    private void jLabel_minimizeClickMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeClickMouseExited
        jLabel_minimizeClick.setIcon(initialIcon_minimize);
    }//GEN-LAST:event_jLabel_minimizeClickMouseExited

    private void jLabel_minimizeClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeClickMouseClicked

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizeClickMouseClicked

    //------------------------------------------------------------Close the form

    private void jLabel_CloseClickMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseClickMouseEntered
        jLabel_CloseClick.setIcon(hoverIcon_close);
    }//GEN-LAST:event_jLabel_CloseClickMouseEntered

    private void jLabel_CloseClickMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseClickMouseExited
        jLabel_CloseClick.setIcon(initialIcon_close);
    }//GEN-LAST:event_jLabel_CloseClickMouseExited

    private void jLabel_CloseClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseClickMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_CloseClickMouseClicked

    //------------------------------------------------previous page butoon label

    private void jLabel_previousPageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_previousPageMouseEntered
        jLabel_previousPage.setIcon(hoverIcon_previous);
    }//GEN-LAST:event_jLabel_previousPageMouseEntered

    private void jLabel_previousPageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_previousPageMouseExited
        jLabel_previousPage.setIcon(initialIcon_previous);
    }//GEN-LAST:event_jLabel_previousPageMouseExited

    private void jLabel_previousPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_previousPageMouseClicked

        WelcomeForm Wf = new WelcomeForm();
        Wf.setVisible(true);
        Wf.pack();
        Wf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel_previousPageMouseClicked

    //--------------------------------------------------------login label button
    private void jLabel_loginButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_loginButtonMouseEntered
        jLabel_loginButton.setIcon(hoverIcon_login);
    }//GEN-LAST:event_jLabel_loginButtonMouseEntered

    private void jLabel_loginButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_loginButtonMouseExited
        jLabel_loginButton.setIcon(initialIcon_login);
    }//GEN-LAST:event_jLabel_loginButtonMouseExited

    private void jLabel_loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_loginButtonMouseClicked

        PreparedStatement st;
        ResultSet rs;

        //get username and password
        String username = jTextField_user.getText();
        String password = String.valueOf(jPasswordField_Pass.getPassword());

        //create a select query to check if the username and the password exist in the currnt database
        String query = "SELECT * FROM `users` WHERE `username` = ? AND `password` = ?";

        try {
            st = db_mathmaze.getConnection().prepareStatement(query);

            st.setString(1, username);
            st.setString(2, password);

            rs = st.executeQuery();

            if (rs.next()) {

                // show the game mode form
                showMessageDialogWithTimer(username);
                
                GameModeForm form = new GameModeForm(username);
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);

                //close the current LoginForm
                this.dispose();

            } else {
                //send error message to the user
                JOptionPane.showMessageDialog(null, "Invalid Username / Password !!! Please enter valid details to login...", "Login Error!", 2);
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jLabel_loginButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1_LoginBackground;
    private javax.swing.JLabel jLabel1_LoginTitle;
    private javax.swing.JLabel jLabel4_LoginUser;
    private javax.swing.JLabel jLabel5_LoginPass;
    private javax.swing.JLabel jLabel6_RegisterLink;
    private javax.swing.JLabel jLabel_CloseClick;
    private javax.swing.JLabel jLabel_RegisterHere;
    private javax.swing.JLabel jLabel_loginButton;
    private javax.swing.JLabel jLabel_minimizeClick;
    private javax.swing.JLabel jLabel_previousPage;
    private javax.swing.JPasswordField jPasswordField_Pass;
    private javax.swing.JTextField jTextField_user;
    // End of variables declaration//GEN-END:variables

    //private Icon setIconImage(String imagesusernamepng) {
    //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    //}
}
