/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mathmaze;

import java.awt.Color;
import java.io.FileNotFoundException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author SANDEEPA
 */
public class RegistrationForm extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationForm
     */
    public RegistrationForm() {
        initComponents();

        //center the form of the window
        this.setLocationRelativeTo(null);

        //create border for the text and password fields
        Border field_border = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.white);
        jTextField_Name.setBorder(field_border);
        jTextField_UserName.setBorder(field_border);
        jPasswordField_Password.setBorder(field_border);
        jPasswordField_ConfirmPassword.setBorder(field_border);

        //create a button group for the radiobuttons
        ButtonGroup bg = new ButtonGroup();
        bg.add(jRadioButton_Male);
        bg.add(jRadioButton_Female);
    }
    // ------------------------------------------------------------------ label buutton images
    ImageIcon initialIcon_register = new ImageIcon("C:\\Users\\sanju\\Documents\\NetBeansProjects\\MathMaze\\src\\images\\LbL_images\\lbl_registerButton.png");
    ImageIcon hoverIcon_register = new ImageIcon("C:\\Users\\sanju\\Documents\\NetBeansProjects\\MathMaze\\src\\images\\LbL_images\\lbl_registerButton_afterClicking.png");

    ImageIcon initialIcon_minimize = new ImageIcon("C:\\Users\\sanju\\Documents\\NetBeansProjects\\MathMaze\\src\\images\\LbL_images\\Minimize button.png");
    ImageIcon hoverIcon_minimize = new ImageIcon("C:\\Users\\sanju\\Documents\\NetBeansProjects\\MathMaze\\src\\images\\LbL_images\\Minimize button after clicking.png");
    
    ImageIcon initialIcon_close = new ImageIcon("C:\\Users\\sanju\\Documents\\NetBeansProjects\\MathMaze\\src\\images\\LbL_images\\Exit button.png");
    ImageIcon hoverIcon_close = new ImageIcon("C:\\Users\\sanju\\Documents\\NetBeansProjects\\MathMaze\\src\\images\\LbL_images\\Exit button after clicking.png");
    
    ImageIcon initialIcon_previous = new ImageIcon("C:\\Users\\sanju\\Documents\\NetBeansProjects\\MathMaze\\src\\images\\LbL_images\\Lbl_button_previous.png");
    ImageIcon hoverIcon_previous = new ImageIcon("C:\\Users\\sanju\\Documents\\NetBeansProjects\\MathMaze\\src\\images\\LbL_images\\Lbl_button_previous_afterClicking.png");
    
    ImageIcon initialIcon_loginNow = new ImageIcon("C:\\Users\\sanju\\Documents\\NetBeansProjects\\MathMaze\\src\\images\\LbL_images\\lbl_Login_Now_button.png");
    ImageIcon hoverIcon_loginNow = new ImageIcon("C:\\Users\\sanju\\Documents\\NetBeansProjects\\MathMaze\\src\\images\\LbL_images\\lbl_Login_Now_button_afterClicking.png");
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_registrationTitle = new javax.swing.JLabel();
        jLabel_Minimize = new javax.swing.JLabel();
        jLabel_Close = new javax.swing.JLabel();
        jLabel_Name = new javax.swing.JLabel();
        jLabel_UserName = new javax.swing.JLabel();
        jLabel__Password = new javax.swing.JLabel();
        jLabel_ConfirmPasswrd = new javax.swing.JLabel();
        jTextField_Name = new javax.swing.JTextField();
        jTextField_UserName = new javax.swing.JTextField();
        jPasswordField_Password = new javax.swing.JPasswordField();
        jPasswordField_ConfirmPassword = new javax.swing.JPasswordField();
        jLabel_Gender = new javax.swing.JLabel();
        jRadioButton_Male = new javax.swing.JRadioButton();
        jRadioButton_Female = new javax.swing.JRadioButton();
        jLabel_LoginHereNow = new javax.swing.JLabel();
        jLabel_Have_a_Account = new javax.swing.JLabel();
        jLabel_registerButton = new javax.swing.JLabel();
        jLabel_previousForm_button = new javax.swing.JLabel();
        jLabel1_RegisterBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_registrationTitle.setFont(new java.awt.Font("Felix Titling", 1, 48)); // NOI18N
        jLabel_registrationTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Register_toMathMaze_Label.png"))); // NOI18N
        getContentPane().add(jLabel_registrationTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 660, 80));

        jLabel_Minimize.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jLabel_Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LbL_images/Minimize button.png"))); // NOI18N
        jLabel_Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_MinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MinimizeMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 40, 40));

        jLabel_Close.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jLabel_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LbL_images/Exit button.png"))); // NOI18N
        jLabel_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 40, 40));

        jLabel_Name.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel_Name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lbl_name.png"))); // NOI18N
        getContentPane().add(jLabel_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 80, 30));

        jLabel_UserName.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel_UserName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lbl_userName.png"))); // NOI18N
        jLabel_UserName.setText("User Name :");
        getContentPane().add(jLabel_UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 140, 30));

        jLabel__Password.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel__Password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lbl_password.png"))); // NOI18N
        getContentPane().add(jLabel__Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 130, 30));

        jLabel_ConfirmPasswrd.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel_ConfirmPasswrd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lbl_confirmPassword.png"))); // NOI18N
        getContentPane().add(jLabel_ConfirmPasswrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 140, 60));

        jTextField_Name.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_Name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField_Name.setText("entername");
        jTextField_Name.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_Name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_NameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_NameFocusLost(evt);
            }
        });
        getContentPane().add(jTextField_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 330, 45));

        jTextField_UserName.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_UserName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField_UserName.setText("enterusername");
        jTextField_UserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_UserNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_UserNameFocusLost(evt);
            }
        });
        getContentPane().add(jTextField_UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 330, 45));

        jPasswordField_Password.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordField_Password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPasswordField_Password.setText("password");
        jPasswordField_Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_PasswordFocusLost(evt);
            }
        });
        getContentPane().add(jPasswordField_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 330, 45));

        jPasswordField_ConfirmPassword.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordField_ConfirmPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPasswordField_ConfirmPassword.setText("confrimpassword");
        jPasswordField_ConfirmPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_ConfirmPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_ConfirmPasswordFocusLost(evt);
            }
        });
        getContentPane().add(jPasswordField_ConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 330, 45));

        jLabel_Gender.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel_Gender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lbl_Gender.png"))); // NOI18N
        jLabel_Gender.setText(" Gender :");
        getContentPane().add(jLabel_Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 100, 30));

        jRadioButton_Male.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jRadioButton_Male.setForeground(new java.awt.Color(51, 255, 255));
        jRadioButton_Male.setSelected(true);
        jRadioButton_Male.setText("Male");
        jRadioButton_Male.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton_Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_MaleActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton_Male, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 100, -1));

        jRadioButton_Female.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jRadioButton_Female.setForeground(new java.awt.Color(51, 255, 255));
        jRadioButton_Female.setText("Female");
        jRadioButton_Female.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton_Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_FemaleActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton_Female, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 110, 30));

        jLabel_LoginHereNow.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel_LoginHereNow.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_LoginHereNow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LbL_images/lbl_Login_Now_button.png"))); // NOI18N
        jLabel_LoginHereNow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_LoginHereNow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_LoginHereNowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_LoginHereNowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_LoginHereNowMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_LoginHereNow, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 550, 180, 40));

        jLabel_Have_a_Account.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel_Have_a_Account.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Label_Do you have an account_.png"))); // NOI18N
        getContentPane().add(jLabel_Have_a_Account, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 550, 360, 40));

        jLabel_registerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LbL_images/lbl_registerButton.png"))); // NOI18N
        jLabel_registerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_registerButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_registerButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_registerButtonMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 270, 80));

        jLabel_previousForm_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LbL_images/Lbl_button_previous.png"))); // NOI18N
        jLabel_previousForm_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_previousForm_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_previousForm_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_previousForm_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_previousForm_buttonMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_previousForm_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 50));

        jLabel1_RegisterBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Background_Registration.png"))); // NOI18N
        getContentPane().add(jLabel1_RegisterBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton_MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_MaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_MaleActionPerformed

    private void jRadioButton_FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_FemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_FemaleActionPerformed

    //----------------------------------------set the minimize icons to the path
    private void jLabel_MinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimizeMouseEntered

        jLabel_Minimize.setIcon(hoverIcon_minimize);
    }//GEN-LAST:event_jLabel_MinimizeMouseEntered

    private void jLabel_MinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimizeMouseExited

        jLabel_Minimize.setIcon(initialIcon_minimize);
    }//GEN-LAST:event_jLabel_MinimizeMouseExited

    //------------------------------------set the close button icons to the path
    private void jLabel_CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseEntered

       jLabel_Close.setIcon(hoverIcon_close);
    }//GEN-LAST:event_jLabel_CloseMouseEntered

    private void jLabel_CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseExited

        jLabel_Close.setIcon(initialIcon_close);
    }//GEN-LAST:event_jLabel_CloseMouseExited

    private void jLabel_MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimizeMouseClicked

        //minimize the form
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_MinimizeMouseClicked

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked

        //close the form
        System.exit(0);
    }//GEN-LAST:event_jLabel_CloseMouseClicked

    // ----------------------------------------------login here now label button
    private void jLabel_LoginHereNowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_LoginHereNowMouseEntered

        jLabel_LoginHereNow.setIcon(hoverIcon_loginNow);
    }//GEN-LAST:event_jLabel_LoginHereNowMouseEntered

    private void jLabel_LoginHereNowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_LoginHereNowMouseExited
        
        jLabel_LoginHereNow.setIcon(initialIcon_loginNow);
    }//GEN-LAST:event_jLabel_LoginHereNowMouseExited

    private void jLabel_LoginHereNowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_LoginHereNowMouseClicked

        //click the login label to log in to Login Form
        LoginForm lf = new LoginForm();
        lf.setVisible(true);
        lf.pack();
        lf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel_LoginHereNowMouseClicked

  // -------------------------------------------------- user input data to name
    private void jTextField_NameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_NameFocusGained

        //clear the textfield on focus if the text is "entername"
        if (jTextField_Name.getText().trim().toLowerCase().equals("entername")) {
            jTextField_Name.setText("");
            jTextField_Name.setForeground(Color.black);
        }
        //add a green layer to the text field
        Border layer = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.green);
        jTextField_Name.setBorder(layer);
    }//GEN-LAST:event_jTextField_NameFocusGained

    private void jTextField_NameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_NameFocusLost
        //if the textfield name is equal to "entername" or empty
        //it will set the "username" text in the field
        if (jTextField_Name.getText().trim().equals("") || jTextField_Name.getText().trim().toLowerCase().equals("entername")) {
            jTextField_Name.setText("entername");
            jTextField_Name.setForeground(new Color(153, 153, 153));
        }
        //create border to text field
        Border layer = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(153, 255, 255));
        jTextField_Name.setBorder(layer);
    }//GEN-LAST:event_jTextField_NameFocusLost

  //----------------------------------------user input user name to the database
    private void jTextField_UserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_UserNameFocusGained

        //clear the textfield on focus if the text is "enterusername"
        if (jTextField_UserName.getText().trim().toLowerCase().equals("enterusername")) {
            jTextField_UserName.setText("");
            jTextField_UserName.setForeground(Color.black);
        }
        //add a green layer to the text field
        Border layer = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.green);
        jTextField_UserName.setBorder(layer);
    }//GEN-LAST:event_jTextField_UserNameFocusGained

    private void jTextField_UserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_UserNameFocusLost

        if (jTextField_UserName.getText().trim().equals("") || jTextField_UserName.getText().trim().toLowerCase().equals("enterusername")) {
            jTextField_UserName.setText("enterusername");
            jTextField_UserName.setForeground(new Color(153, 153, 153));
        }
        //create border to text field
        Border layer = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(153, 255, 255));
        jTextField_UserName.setBorder(layer);
    }//GEN-LAST:event_jTextField_UserNameFocusLost

   //--------------------------------- ------------------------------user password input
    private void jPasswordField_PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_PasswordFocusGained

        if (jPasswordField_Password.getText().trim().toLowerCase().equals("password")) {
            jPasswordField_Password.setText("");
            jPasswordField_Password.setForeground(Color.black);
        }
        //add a green layer to the text field
        Border layer = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.green);
        jPasswordField_Password.setBorder(layer);

    }//GEN-LAST:event_jPasswordField_PasswordFocusGained

    private void jPasswordField_PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_PasswordFocusLost

        if (jPasswordField_Password.getText().trim().equals("") || jPasswordField_Password.getText().trim().toLowerCase().equals("password")) {
            jPasswordField_Password.setText("password");
            jPasswordField_Password.setForeground(new Color(153, 153, 153));
        }
        Border layer = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(153, 255, 255));
        jPasswordField_Password.setBorder(layer);
    }//GEN-LAST:event_jPasswordField_PasswordFocusLost

    //------------------ --------- ------------------------------confirm password field
    private void jPasswordField_ConfirmPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_ConfirmPasswordFocusGained

        if (jPasswordField_ConfirmPassword.getText().trim().toLowerCase().equals("confrimpassword")) {
            jPasswordField_ConfirmPassword.setText("");
            jPasswordField_ConfirmPassword.setForeground(Color.black);
        }
        //add a green layer to the text field
        Border layer = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.green);
        jPasswordField_ConfirmPassword.setBorder(layer);
    }//GEN-LAST:event_jPasswordField_ConfirmPasswordFocusGained

    private void jPasswordField_ConfirmPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_ConfirmPasswordFocusLost

        if (jPasswordField_ConfirmPassword.getText().trim().equals("") || jPasswordField_ConfirmPassword.getText().trim().toLowerCase().equals("confrimpassword")) {
            jPasswordField_ConfirmPassword.setText("confrimpassword");
            jPasswordField_ConfirmPassword.setForeground(new Color(153, 153, 153));
        }
        Border layer = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(153, 255, 255));
        jPasswordField_ConfirmPassword.setBorder(layer);

    }//GEN-LAST:event_jPasswordField_ConfirmPasswordFocusLost

    // ----------------------------------------------register user from the label
    
    private void jLabel_registerButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_registerButtonMouseEntered
        
        jLabel_registerButton.setIcon(hoverIcon_register);
    }//GEN-LAST:event_jLabel_registerButtonMouseEntered

    private void jLabel_registerButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_registerButtonMouseExited
        
        jLabel_registerButton.setIcon(initialIcon_register);
    }//GEN-LAST:event_jLabel_registerButtonMouseExited

    private void jLabel_registerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_registerButtonMouseClicked
        
        // get data from fields
        String full_name = jTextField_Name.getText();
        String username = jTextField_UserName.getText();
        String password = String.valueOf(jPasswordField_Password.getPassword());
        String con_pass = String.valueOf(jPasswordField_ConfirmPassword.getPassword());
        String gender = "Male";

        if (jRadioButton_Female.isSelected()) {
            gender = "Female";
        }

        if (verifyFields()) {
            if (!checkUsername(username)) {
                PreparedStatement ps;
                ResultSet rs; 
                
                 String registerUser_Query = "INSERT INTO `users`(`full_name`, `username`, `password`, `gender`) VALUES (?,?,?,?)";
                //String registerUser_Query = "INSERT INTO `users`(`full_name`, `username`, `password`, `gender`,`score`,`time`) VALUES (?,?,?,?,0,0)";
                //INSERT INTO `users`(`full_name`, `username`, `password`, `gender`) VALUES (?,?,?,?)
                //INSERT INTO `users`(`full_name`, `username`, `password`, `gender`, `score`, `time`) VALUES (?,?,?,?,?,?)
                //String registerUser_Query = "INSERT INTO `users`(`full_name`, `username`, `password`, `gender`) VALUES (?,?,?,?)";

                try {
                    ps = db_mathmaze.getConnection().prepareStatement(registerUser_Query);
                    ps.setString(1, full_name);
                    ps.setString(2, username);
                    ps.setString(3, password);
                    ps.setString(4, gender);

                    if (ps.executeUpdate() != 0) {
                        JOptionPane.showMessageDialog(null, "Your account has been created. Enjoy your game!", "Congratulations!!!", JOptionPane.INFORMATION_MESSAGE);

                        // Move to the login page
                        LoginForm Lf = new LoginForm();
                        Lf.setVisible(true);
                        Lf.pack();
                        Lf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "There is an error in inputted data! Please check your details again", "Registration Error!", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }//GEN-LAST:event_jLabel_registerButtonMouseClicked

    // ------------------------------------------------------previous page enter
    
    private void jLabel_previousForm_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_previousForm_buttonMouseEntered
        
        jLabel_previousForm_button.setIcon(hoverIcon_previous);
    }//GEN-LAST:event_jLabel_previousForm_buttonMouseEntered

    private void jLabel_previousForm_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_previousForm_buttonMouseExited
        
        jLabel_previousForm_button.setIcon(initialIcon_previous);
    }//GEN-LAST:event_jLabel_previousForm_buttonMouseExited

    private void jLabel_previousForm_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_previousForm_buttonMouseClicked
       
        WelcomeForm Wf = new WelcomeForm();
        Wf.setVisible(true);
        Wf.pack();
        Wf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel_previousForm_buttonMouseClicked

    // --------------------------------create a function to verify the empty fields  
    public boolean verifyFields() {
        String full_name = jTextField_Name.getText();
        String username = jTextField_UserName.getText();
        String password = String.valueOf(jPasswordField_Password.getPassword());
        String con_pass = String.valueOf(jPasswordField_ConfirmPassword.getPassword());

        // check empty fields
        if (full_name.trim().equals("") || username.trim().equals("") || password.trim().equals("") || con_pass.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Check your Fields. One or More fields are empty", "Empty Fields", 2);
            return false;
        } else if (!password.equals(con_pass)) {
            // check if the two password are equals or not
            JOptionPane.showMessageDialog(null, "Your Password doesn't Match. Please check!", "Confirm Password", 2);
            return false;
        } else {
            // if everything fine
            return true;
        }
    }

    //-----create a function to check if the entered username already exists in the database
    public boolean checkUsername(String username) {
        PreparedStatement st;
        ResultSet rs;
        boolean username_exist = false;

        //SELECT * FROM `users` WHERE `username` = ?
        String query = "SELECT * FROM `users` WHERE `username` = ?";

        try {
            st = db_mathmaze.getConnection().prepareStatement(query);
            st.setString(1, username); // Corrected line
            rs = st.executeQuery();

            if (rs.next()) {
                username_exist = true;
                JOptionPane.showMessageDialog(null, "This Username is already taken, Choose another one!", "Username Invalid", 2);
            }

        } catch (SQLException ex) {
            Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        return username_exist;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1_RegisterBackground;
    private javax.swing.JLabel jLabel_Close;
    private javax.swing.JLabel jLabel_ConfirmPasswrd;
    private javax.swing.JLabel jLabel_Gender;
    private javax.swing.JLabel jLabel_Have_a_Account;
    private javax.swing.JLabel jLabel_LoginHereNow;
    private javax.swing.JLabel jLabel_Minimize;
    private javax.swing.JLabel jLabel_Name;
    private javax.swing.JLabel jLabel_UserName;
    private javax.swing.JLabel jLabel__Password;
    private javax.swing.JLabel jLabel_previousForm_button;
    private javax.swing.JLabel jLabel_registerButton;
    private javax.swing.JLabel jLabel_registrationTitle;
    private javax.swing.JPasswordField jPasswordField_ConfirmPassword;
    private javax.swing.JPasswordField jPasswordField_Password;
    private javax.swing.JRadioButton jRadioButton_Female;
    private javax.swing.JRadioButton jRadioButton_Male;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextField jTextField_UserName;
    // End of variables declaration//GEN-END:variables
}
