/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mathmaze;

import java.awt.Color;
import java.awt.Component;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author SANDEEPA
 */
public class WelcomeForm extends javax.swing.JFrame {
    
    /**
     * Creates new form WelcomForm
     */
    public WelcomeForm() {
        initComponents();
        
        //center the form
        this.setLocationRelativeTo(null);
        
        // Initialize form
    }
   //--------------------------------------------------------------- -----image location 
    ImageIcon initialIcon = new ImageIcon("C:\\Users\\sanju\\Documents\\NetBeansProjects\\MathMaze\\src\\images\\LbL_images\\Button_lbl_Login.png");
    ImageIcon hoverIcon = new ImageIcon("C:\\Users\\sanju\\Documents\\NetBeansProjects\\MathMaze\\src\\images\\LbL_images\\Button_lbl_Login_afterClicking.png");
    
    ImageIcon initialIcon_register = new ImageIcon("C:\\Users\\sanju\\Documents\\NetBeansProjects\\MathMaze\\src\\images\\LbL_images\\Button_lbl_Register.png");
    ImageIcon hoverIcon_register = new ImageIcon("C:\\Users\\sanju\\Documents\\NetBeansProjects\\MathMaze\\src\\images\\LbL_images\\Button_lbl_Register_afterClicking.png");
    
    ImageIcon initialIcon_rules = new ImageIcon("C:\\Users\\sanju\\Documents\\NetBeansProjects\\MathMaze\\src\\images\\LbL_images\\Button_lbl_Rules.png");
    ImageIcon hoverIcon_rules = new ImageIcon("C:\\Users\\sanju\\Documents\\NetBeansProjects\\MathMaze\\src\\images\\LbL_images\\Button_lbl_Rules_afterClicking.png");
    
    ImageIcon initialIcon_minimize = new ImageIcon("C:\\Users\\sanju\\Documents\\NetBeansProjects\\MathMaze\\src\\images\\LbL_images\\Minimize button.png");
    ImageIcon hoverIcon_minimize = new ImageIcon("C:\\Users\\sanju\\Documents\\NetBeansProjects\\MathMaze\\src\\images\\LbL_images\\Minimize button after clicking.png");
   
    ImageIcon initialIcon_close = new ImageIcon("C:\\Users\\sanju\\Documents\\NetBeansProjects\\MathMaze\\src\\images\\LbL_images\\Exit button.png");
    ImageIcon hoverIcon_close = new ImageIcon("C:\\Users\\sanju\\Documents\\NetBeansProjects\\MathMaze\\src\\images\\LbL_images\\Exit button after clicking.png");
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2_welcome = new javax.swing.JLabel();
        jLabel_LoginClick = new javax.swing.JLabel();
        jLabel_RegisterClick = new javax.swing.JLabel();
        jLabel_RulesClick = new javax.swing.JLabel();
        jLabel_MinimizeClick = new javax.swing.JLabel();
        jLabel_CloseClick = new javax.swing.JLabel();
        jLabel1_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2_welcome.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2_welcome.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 40)); // NOI18N
        jLabel2_welcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Label_Welcome to Math Maze.png"))); // NOI18N
        getContentPane().add(jLabel2_welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 820, 90));

        jLabel_LoginClick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LbL_images/Button_lbl_Login.png"))); // NOI18N
        jLabel_LoginClick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_LoginClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_LoginClickMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_LoginClickMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_LoginClickMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_LoginClick, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, 90));

        jLabel_RegisterClick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LbL_images/Button_lbl_Register.png"))); // NOI18N
        jLabel_RegisterClick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_RegisterClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_RegisterClickMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_RegisterClickMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_RegisterClickMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_RegisterClick, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 250, 100));

        jLabel_RulesClick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LbL_images/Button_lbl_Rules.png"))); // NOI18N
        jLabel_RulesClick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_RulesClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_RulesClickMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_RulesClickMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_RulesClickMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_RulesClick, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 250, 90));

        jLabel_MinimizeClick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LbL_images/Minimize button.png"))); // NOI18N
        jLabel_MinimizeClick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_MinimizeClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MinimizeClickMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_MinimizeClickMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MinimizeClickMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_MinimizeClick, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 40, 40));

        jLabel_CloseClick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LbL_images/Exit button.png"))); // NOI18N
        jLabel_CloseClick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_CloseClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseClickMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_CloseClickMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_CloseClickMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_CloseClick, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 40, 40));

        jLabel1_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Background_welcome.png"))); // NOI18N
        getContentPane().add(jLabel1_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //---------------------------------------------------------Login Function label
    
    private void jLabel_LoginClickMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_LoginClickMouseEntered
        
        jLabel_LoginClick.setIcon(hoverIcon);
    }//GEN-LAST:event_jLabel_LoginClickMouseEntered

    private void jLabel_LoginClickMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_LoginClickMouseExited
        
        jLabel_LoginClick.setIcon(initialIcon);
    }//GEN-LAST:event_jLabel_LoginClickMouseExited

    private void jLabel_LoginClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_LoginClickMouseClicked
        
        LoginForm Lf = new LoginForm();
        Lf.setVisible(true);
        Lf.pack();
        Lf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel_LoginClickMouseClicked

    // --------------------------------------------------------Register Function Label
    
    private void jLabel_RegisterClickMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RegisterClickMouseEntered
        
        jLabel_RegisterClick.setIcon(hoverIcon_register);
    }//GEN-LAST:event_jLabel_RegisterClickMouseEntered

    private void jLabel_RegisterClickMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RegisterClickMouseExited
        
        jLabel_RegisterClick.setIcon(initialIcon_register);
    }//GEN-LAST:event_jLabel_RegisterClickMouseExited

    private void jLabel_RegisterClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RegisterClickMouseClicked
        
        RegistrationForm Rf = new RegistrationForm();
        Rf.setVisible(true);
        Rf.pack();
        Rf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel_RegisterClickMouseClicked

    
    //------------------------------------------------------------------minimize form
    private void jLabel_MinimizeClickMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimizeClickMouseEntered
        jLabel_MinimizeClick.setIcon(hoverIcon_minimize);
    }//GEN-LAST:event_jLabel_MinimizeClickMouseEntered

    private void jLabel_MinimizeClickMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimizeClickMouseExited
        jLabel_MinimizeClick.setIcon(initialIcon_minimize);
    }//GEN-LAST:event_jLabel_MinimizeClickMouseExited

    private void jLabel_MinimizeClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimizeClickMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_MinimizeClickMouseClicked

    //--------------------------------------------------------Close the current form
    private void jLabel_CloseClickMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseClickMouseEntered
        jLabel_CloseClick.setIcon(hoverIcon_close);
    }//GEN-LAST:event_jLabel_CloseClickMouseEntered

    private void jLabel_CloseClickMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseClickMouseExited
        jLabel_CloseClick.setIcon(initialIcon_close);
    }//GEN-LAST:event_jLabel_CloseClickMouseExited

    private void jLabel_CloseClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseClickMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_CloseClickMouseClicked

    // -------------------------------------------------------------Rules form 
    
    private void jLabel_RulesClickMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RulesClickMouseEntered
        jLabel_RulesClick.setIcon(hoverIcon_rules);
    }//GEN-LAST:event_jLabel_RulesClickMouseEntered

    private void jLabel_RulesClickMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RulesClickMouseExited
        jLabel_RulesClick.setIcon(initialIcon_rules);
    }//GEN-LAST:event_jLabel_RulesClickMouseExited

    private void jLabel_RulesClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RulesClickMouseClicked
        
        RulesForm rulesf = new RulesForm();
        rulesf.setVisible(true);
        rulesf.pack();
        rulesf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_jLabel_RulesClickMouseClicked
/**/
    /**/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1_background;
    private javax.swing.JLabel jLabel2_welcome;
    private javax.swing.JLabel jLabel_CloseClick;
    private javax.swing.JLabel jLabel_LoginClick;
    private javax.swing.JLabel jLabel_MinimizeClick;
    private javax.swing.JLabel jLabel_RegisterClick;
    private javax.swing.JLabel jLabel_RulesClick;
    // End of variables declaration//GEN-END:variables
}
